[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn mbti_hub.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/api/home/"
healthcheckTimeout = 300

[[services]]
name = "mbti_hub"
sourceDir = "server"

[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = [
    "python -m venv /opt/venv",
    "source /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "source /opt/venv/bin/activate && python manage.py collectstatic --noinput"
]

[start]
cmd = "source /opt/venv/bin/activate && python manage.py migrate && python manage.py seed_data && gunicorn mbti_hub.wsgi:application --bind 0.0.0.0:$PORT"