[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn mbti_hub.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/api/home/"
healthcheckTimeout = 300

[[services]]
name = "mbti_hub"
sourceDir = "server"