# Generated by Django 5.0 on 2025-08-14 02:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='카테고리명')),
                ('emoji', models.CharField(max_length=10, verbose_name='이모지')),
                ('description', models.TextField(verbose_name='설명')),
                ('color', models.CharField(max_length=50, verbose_name='색상 클래스')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리들',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='테스트 제목')),
                ('description', models.TextField(verbose_name='테스트 설명')),
                ('estimated_time', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='예상 소요시간(분)')),
                ('difficulty', models.CharField(choices=[('easy', '쉬움'), ('medium', '보통'), ('hard', '어려움')], default='medium', max_length=10, verbose_name='난이도')),
                ('thumbnail', models.CharField(blank=True, max_length=10, verbose_name='썸네일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='api.category', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '테스트',
                'verbose_name_plural': '테스트들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='질문 내용')),
                ('order', models.PositiveIntegerField(verbose_name='순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.test', verbose_name='테스트')),
            ],
            options={
                'verbose_name': '질문',
                'verbose_name_plural': '질문들',
                'ordering': ['test', 'order'],
                'unique_together': {('test', 'order')},
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbti_type', models.CharField(max_length=4, verbose_name='MBTI 유형')),
                ('title', models.CharField(max_length=200, verbose_name='결과 제목')),
                ('description', models.TextField(verbose_name='결과 설명')),
                ('characteristics', models.JSONField(verbose_name='특징')),
                ('strengths', models.JSONField(verbose_name='강점')),
                ('weaknesses', models.JSONField(verbose_name='약점')),
                ('compatibility', models.JSONField(verbose_name='궁합')),
                ('percentage', models.JSONField(verbose_name='퍼센테이지')),
                ('answers', models.JSONField(verbose_name='답변')),
                ('time_spent', models.PositiveIntegerField(verbose_name='소요시간(초)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.test', verbose_name='테스트')),
            ],
            options={
                'verbose_name': '테스트 결과',
                'verbose_name_plural': '테스트 결과들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='옵션 내용')),
                ('order', models.PositiveIntegerField(verbose_name='순서')),
                ('scores', models.JSONField(verbose_name='MBTI 점수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.question', verbose_name='질문')),
            ],
            options={
                'verbose_name': '질문 옵션',
                'verbose_name_plural': '질문 옵션들',
                'ordering': ['question', 'order'],
                'unique_together': {('question', 'order')},
            },
        ),
    ]
