[phases.setup]
nixPkgs = ["python312", "pip"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[start]
cmd = "gunicorn mbti_hub.wsgi:application --bind 0.0.0.0:$PORT"