[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = [
    "python -m venv /opt/venv",
    "source /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "source /opt/venv/bin/activate && python manage.py collectstatic --noinput"
]

[start]
cmd = "source /opt/venv/bin/activate && gunicorn mbti_hub.wsgi:application --bind 0.0.0.0:$PORT"